### ISSUE TITLE
【已解决】错别字

### ISSUE THREAD

**Issue by LOL808** [QianMo/Game-Programmer-Study-Notes#1]
https://github.com/QianMo/Game-Programmer-Study-Notes/tree/master/Content/%E3%80%8AReal-Time%20Rendering%203rd%E3%80%8B%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0/Content/BlogPost02
2.4 光栅化阶段 The Rasterizer Stage

给定经过变换和投影之后的顶点，颜色以及纹理坐标（均来自于几何阶段），给每个像素（Pixel）正确配色，以便正确绘制整幅图像。这个过个过程叫光珊（栅）化（rasterization）或扫描变换（scan conversion），即从二维顶点所处的屏幕空间（所有顶点都包含Z值即深度值，及各种与相关的着色信息）到屏幕上的像素的转换。

**Comment by QianMo** [comment]
谢谢勘误，已修正。
