### ISSUE TITLE
【已解决】超链接错误

### ISSUE THREAD

**Issue by SuperSodaSea** [QianMo/Game-Programmer-Study-Notes#4]
在 [《GPU Gems 1》全书核心内容提炼总结 / 二十六、OpenEXR图像文件格式](https://github.com/QianMo/Game-Programmer-Study-Notes/blob/master/Content/%E3%80%8AGPU%20Gems%201%E3%80%8B%E5%85%A8%E4%B9%A6%E6%8F%90%E7%82%BC%E6%80%BB%E7%BB%93/README.md#%E6%A0%B8%E5%BF%83%E8%A6%81%E7%82%B9-20) 中，有一处超链接格式有误：

> OpenEXR网站是 www.openexr.org，上面有关于此格式的全部细节。

其后的中文被识别为网址的一部分，导致出错。在网址后加一个空格，改为：

> OpenEXR网站是 www.openexr.org ，上面有关于此格式的全部细节。

即可解决。

**Comment by QianMo** [comment]
已解决，谢谢勘误。
