### ISSUE TITLE
[Typo] GPU Gems1 中环绕照明笔误

### ISSUE THREAD

**Issue by RidgeSTD** [QianMo/Game-Programmer-Study-Notes#9]
感谢读书笔记，拜读收益颇多。
提一个小笔误：在《GPU Gem1》全书提炼总结中环绕照明"warp lighting"写成了"warp lighting"

**Comment by QianMo** [comment]
感谢勘误

**Comment by zinwalin** [comment]
> 环绕照明"warp lighting"写成了"warp lighting"

环绕照明"warp lighting"写成了"warp lighting"?  　没看懂。
